### PR TITLE
feat(rbac): Add Aggregated ClusterRoles

### PR DESCRIPTION
**Pull request by sathish-thangaraj**
Add Aggregated ClusterRoles 
Examples for aggregated cluster roles
Contributes to RBAC

### CODE REVIEW

**Comment by mhausenblas** [comment]
Thanks a lot for the contribution @sathish-thangaraj and I will: 1. verify ASAP, and 2. add a new contributor file where I'll add you. In the meantime, can I ask you to please provide a DCO?

**Comment by sathish-thangaraj** [comment]
@mhausenblas Thanks , I did sign-off the commit.

**Comment by mhausenblas** [comment]
Thanks a lot! Also, added you to https://github.com/mhausenblas/rbacadabra/blob/master/docs/contribs.md ;)

**Comment by mhausenblas** [comment]
And it's live now https://recipes.rbac.dev/#aggregate-roles

**Pull request merged**
